---
title: "psychometric analysis"
output: html_document
---

```{r,include = FALSE}
library(tidyverse)
library(ggplot2)
library(rstatix)
library(quickpsy)
library(ggpubr)
library(rstatix)
library(GGally)
library(gridExtra)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```

#### Adult's fitting of Psychometric curves

```{r}

### fitting of a psychometric curve for each difficulty and for each subject with a chance level at 25%
fit <- quickpsy(data_psycurves, SNRdB, nbrepval, nbreptot, grouping = .(ID, difficulty),guess = 0.25,bootstrap = "nonparametric") 
save(fit,file = 'fit_quickpsy')

### stores results of the non-parametric bootsrap threshold comparison in tc_comp
tc_comp = subset(fit$thresholdcomparisons, ID == ID2)

### stores discrimination thresholds in the thre variable
thre = fit$thresholds

```

```{r figures of each psychometric curve per subject and per condition of difficulty}

load('fit_quickpsy')

fit$averages$ID_num = as.numeric(fit$averages$ID)
fit$averages$ID_num = as.factor(as.character(fit$averages$ID_num))
fit$averages$ID_num <- factor(fit$averages$ID_num, levels = as.character(1:length(levels(fit$averages$ID_num))))
fit$curves$ID_num = as.numeric(fit$curves$ID)
fit$curves$ID_num = as.factor(as.character(fit$curves$ID_num))
fit$curves$ID_num <- factor(fit$curves$ID_num, levels = as.character(1:length(levels(fit$averages$ID_num))))
fit$thresholds$ID_num = as.numeric(fit$thresholds$ID)
fit$thresholds$ID_num = as.factor(as.character(fit$thresholds$ID_num))
fit$thresholds$ID_num <- factor(fit$thresholds$ID_num, levels = as.character(1:length(levels(fit$averages$ID_num))))

psycurve_figure_final = ggplot() +
  facet_wrap( ~ ID_num,nrow = 4,ncol=6,scales = "free") +
  geom_point(data = fit$averages, 
             aes(x = SNRdB, y = prob, color = factor(difficulty))) +
  geom_line(data = fit$curves, 
            aes(x = x, y = y, color = factor(difficulty))) +
  ylab("Proportion correct") +
  xlab("SNR (dB)") +
  scale_x_continuous(limits=c(-15,15)) +
  geom_linerange(data = fit$thresholds, 
                 aes(x = thre, ymin = 0, ymax = prob, color = factor(difficulty)), lty =2,size = 0.75) +
  scale_color_manual(breaks = c("easy","difficult"),values=c(cbPalette[2],cbPalette[6]), name = "Difficulty", labels = c("Easy","Difficult")) +
  theme_classic() +
  theme(axis.text.x = element_text(size=12),axis.text.y = element_text(size=15), panel.spacing = unit(1, "lines"),axis.title = element_text(size=20),strip.text.x = element_text(size = 15),legend.text=element_text(size=18),legend.title=element_text(size=18))
psycurve_figure_final

ggsave("psycurve_figure_final.png", plot = psycurve_figure_final,device = "png",width = 15,height = 7)
```



```{r Plots thresholds}
thre_figure = ggplot(data = thre, aes(x=difficulty,y=thre)) + geom_boxplot(data = thre, aes(x=difficulty,y=thre),lwd=1.5,width = 0.5)  + scale_x_discrete(limits = c("easy","difficult"),labels = c("Easy","Difficult")) + 
  geom_line(aes(group=ID)) +
ylab(label ="Detection Threshold \n (Signal/Noise Ratio)") + xlab("Difficulty") +   theme_light() +
  theme_classic() + theme(axis.text=element_text(size=15),axis.title=element_text(size=20)) 

ggsave("thre_figure.png", plot = thre_figure,device = "png")
ggsave("thre_figure.svg", plot = thre_figure,device = "svg")

```
#### Adult's discrimination thresholds comparison

```{r stats analysis}
shapiro.test(thre$thre)

pairwise_t_test(thre,thre ~ difficulty, paired = T)
```


```{r figures of threshold comparison}
thre_figure = ggplot(data = thre, aes(x=difficulty,y=thre)) + geom_boxplot(data = thre, aes(x=difficulty,y=thre),lwd=1.5,width = 0.5)  + 
  scale_x_discrete(limits = c("easy","difficult"),labels = c("Easy","Difficult")) + 
  geom_line(aes(group=ID)) +
  ylab(label ="Detection Threshold \n (Signal/Noise Ratio)") + 
  xlab("Difficulty") +   theme_light() +
  theme_classic() + 
  theme(axis.text=element_text(size=15),axis.title=element_text(size=20)) 

ggsave("thre_figure.png", plot = thre_figure,device = "png",height = 7)
```
#### Adult's summed psychometric fit

```{r psychometric fit of the summed responses}
### creation of a table where all adult's performance are summed so that we create an "overall adult" subject
data_psycurves_final_bis %>%
  group_by(SNRdB,difficulty) %>%
  summarise(nbrepval = sum(nbrepval),nbreptot = sum(nbreptot)) -> data_psycurves_final_summed

### fit of the "overall" adult for each difficulty condition
fit_summed <- quickpsy(data_psycurves_final_summed, SNRdB, nbrepval, nbreptot, grouping = .(difficulty),guess = 0.25,bootstrap = "nonparametric") 
save(fit_summed,file = 'fit_quickpsy_summed')

### stores results of the non-parametric bootsrap threshold comparison in tc_comp
tc = fit_summed$thresholdcomparisons

### stores discrimination thresholds in the thre variable
thre = fit_summed$thresholds
```



#### Projection of children's performance on summed adult's psychometric fit


```{r}

### First plot of average accuracy across age group (stored in table_mean_grade dataframe) projected on the summed psychometric fit of adults
#### for the -3 dB SNR of children's data
proj_plot_m3 = ggplot() +
  geom_point(data = subset(fit_summed$averages), 
             aes(x = SNRdB, y = prob, color = difficulty), show.legend = F,size = 3,shape = 17) +
  geom_line(data = subset(fit_summed$curves), 
            aes(x = x, y = y,color = difficulty),size = 1) +
  geom_linerange(data = subset(table_mean_grade,SNRdB == -3), 
                 aes(x = snr, ymin = 0, ymax = perf, linetype = grade, color = difficulty),size = 0.8,show.legend = F) +
  geom_linerangeh(data = subset(table_mean_grade,SNRdB == -3), 
                 aes(y = perf, xmin = -15, xmax = snr, linetype = grade, color = difficulty),size = 0.8) +
    geom_vline(xintercept = -3,linetype = "dashed",alpha=0.4,size = 1.2) +
    scale_color_manual(values = c("#d8b365", "#5ab4ac"),name = "Difficulty", labels = c("Easy","Difficult")) +
    scale_linetype_manual(name = "Grade", values = seq(1,6),labels = c("KG","1st","2nd","3rd","4th","5th")) +
      scale_x_continuous(limits=c(-15,15),breaks = seq(-12,9,3)) +
    facet_grid(~difficulty) +
  guides(linetype=guide_legend(keywidth = 3, keyheight = 1),
          color=guide_legend(keywidth = 3, keyheight = 1)) +
  theme_classic() +
  theme(strip.text = element_blank(), axis.title = element_blank(), axis.text = element_text(size = 16),
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', colour=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill='transparent',colour = NA),
        legend.box.background = element_rect(fill='transparent'))

#### for the +3 dB SNR of children's data
proj_plot_p3 = ggplot() +
  geom_point(data = subset(fit_summed$averages), 
             aes(x = SNRdB, y = prob, color = difficulty), show.legend = F,size = 3,shape = 17) +
  geom_line(data = subset(fit_summed$curves), 
            aes(x = x, y = y,color = difficulty),size = 1) +
  geom_linerange(data = subset(table_mean_grade,SNRdB == 3), 
                 aes(x = snr, ymin = 0, ymax = perf, linetype = grade, color = difficulty),size = 0.8,show.legend = F) +
  geom_linerangeh(data = subset(table_mean_grade,SNRdB == 3), 
                 aes(y = perf, xmin = -15, xmax = snr, linetype = grade, color = difficulty),size = 0.8) +
    geom_vline(xintercept = 3,linetype = "dashed",alpha=0.4,size = 1.2) +
    scale_color_manual(values = c("#d8b365", "#5ab4ac"),name = "Difficulty", labels = c("Easy","Difficult")) +
    scale_linetype_manual(name = "Grade", values = seq(1,6),labels = c("KG","1st","2nd","3rd","4th","5th")) +
      scale_x_continuous(limits=c(-15,15),breaks = seq(-12,9,3)) +
    facet_grid(~difficulty) +
  guides(linetype=guide_legend(keywidth = 3, keyheight = 1),
          color=guide_legend(keywidth = 3, keyheight = 1)) +
  theme_classic() +
  theme(strip.text = element_blank(), axis.title = element_blank(), axis.text = element_text(size = 16),
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', colour=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill='transparent',colour = NA),
        legend.box.background = element_rect(fill='transparent'))
  

### Arrangement of the final figure  
proj_panels = ggarrange(proj_plot_p3,proj_plot_m3,nrow = 2, common.legend = T,legend = "right")
proj_panels = annotate_figure(proj_panels, left = textGrob("Proportion of correct responses", rot = 90, vjust = 0.25, gp = gpar(cex = 2.2)),
                    bottom = textGrob("SNR during adult data collection", gp = gpar(cex = 2.2)))
ggsave("proj_panels.png", proj_panels,device = "png", width = 12)
```


##### Calculation of each child's SRT for litterature comparison

```{r}

##### For each child, we add to the average performance dataframe (glm_table_prop) 2 points: one at -15 dB SNR for a 25% accuracy and one at +15 dB SNR for a 100% accuracy
for (i in 1:length(unique(glm_table_prop$ID))){
   which_row = which(as.character(glm_table_prop$ID) == as.character(unique(glm_table_prop$ID)[i]))
   glm_table_prop %>%
     slice(rep(which_row[1],2)) -> to_change
   to_change[1,"difficulty"] = "easy"
   to_change[2,"difficulty"] = "easy"
   to_change[1,"SNRdB"] = -15
   to_change[2,"SNRdB"] = 15
   to_change[1,"count"] = 6
   to_change[2,"count"] = 24
   to_change[1,"num_tot"] = 24
   to_change[2,"num_tot"] = 24
   to_change[1,"freq"] = 0.25
   to_change[2,"freq"] = 1
   to_change %>%
     bind_rows(to_change) -> to_change
   to_change[3,"difficulty"] = "difficult"
   to_change[4,"difficulty"] = "difficult"
   glm_table_prop %>%
     bind_rows(to_change) -> glm_table_prop
}


```

```{r}
#### psychometric fit or each child for each difficulty condition
fit_children <- quickpsy(glm_table_prop, SNRdB, count, num_tot, grouping = .(ID, difficulty),guess = 0.25,bootstrap = "none") 
save(fit_children,file = 'fit_children')

thre_children = fit_children$thre
```

#### Comparison figure between children's SRT and data from Buss et al (2017)
```{r}
#### in a dataframe containing the mean thresholds from adults, adding of a x variable with (16,16) coordinates to place it on the right on the figure
thre_mean_adults$x = c(16,16) 
thre_children$difficulty = factor(thre_children$difficulty, levels = c("easy","difficult"))

### figure of children and average adult's SRT in function of log(Age)
thre_children_figure = ggplot(subset(thre_children), aes(x=log(age_in_months/12), y=thre, colour = difficulty, fill = difficulty)) + 
  geom_smooth(method="lm") +
  geom_pointrange(data = thre_mean_adults,aes(x=log(x),y=y,ymin =y - st_de, ymax = y+st_de,colour = difficulty,group = difficulty),size=1.3) +
  theme_classic() +
  ggtitle("Current study: Sixteen-talker noise",subtitle = "Children: n = 95, Adults: n = 19")+
  xlab("Age (months)") +
  ylab("Perception thresholds (dB SNR)") +
  scale_color_manual(values = c("#d8b365", "#5ab4ac"),name = "Difficulty", labels = c("Easy","Difficult")) +
    scale_fill_manual(values=c("#d8b365", "#5ab4ac"),name = "Difficulty", labels = c("Easy","Difficult")) +
  scale_shape_discrete(name = "Difficulty", labels = c("Easy","Difficult")) +
  theme(axis.text=element_text(size=15),axis.title=element_blank(),legend.text=element_text(size=18),legend.title=element_text(size=18),plot.title = element_text(size = 20, face = "bold",hjust = 0.5),legend.position="none",plot.subtitle = element_text(size = 14),
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', colour=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill='transparent',colour = NA),
        legend.box.background = element_rect(fill='transparent'))+
   scale_x_continuous(breaks = c(1.609438,1.945910,2.197225,2.397895,2.564949,2.772589), labels = c("5","7","9","11","13","adults"), limits = c(1.504077 ,2.772589)) +
    ylim(-14,7)
thre_children_figure

 
#### in a dataframe containing Buss et al (2017)'s adults data, adding of a x variable with (16,16) coordinates for adults to place it on the right on the figure

all_points_ss_adults$x = c(16,16)
all_points_tt_adults$x = c(16,16)

### figure of Buss et al (2017)'s children and average adult's SRT in function of log(Age) for Speech-shaped noise
buss_ss_fig = ggplot(subset(all_points_ss), aes(x=log(x), y=y-60, color = cond, fill = cond)) + 
    xlab("Age (months)") +
  ylab("Perception thresholds (dB SNR)") +
   ggtitle("Buss et al. 2016: Speech-shaped noise",subtitle = "Children: n = 16, Adults: n = 10")+
   geom_smooth(method="lm") +
   geom_point(data = all_points_ss_adults, mapping = aes(x = log(x)),size = 6) +
   scale_color_manual(values = c("#d8b365", "#5ab4ac"),name = "Difficulty", labels = c("Easy","Difficult")) +
   scale_fill_manual(values=c("#d8b365", "#5ab4ac"),name = "Difficulty", labels = c("Easy","Difficult")) +
   theme_classic() +
   theme(axis.text=element_text(size=15),axis.title=element_blank(),legend.text=element_text(size=18),legend.title=element_text(size=18),plot.title = element_text(size = 20, face = "bold",hjust = 0.5),legend.position="none",plot.subtitle = element_text(size = 14),
         panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', colour=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill='transparent',colour = NA),
        legend.box.background = element_rect(fill='transparent')) +
   scale_x_continuous(breaks =  c(1.609438,1.945910,2.197225,2.397895,2.564949,2.772589), labels = c("5","7","9","11","13","adults"), limits = c(1.504077 ,2.772589)) +
    ylim(-14,7)

### figure of Buss et al (2017)'s children and average adult's SRT in function of log(Age) for Two-talker babble-noise

buss_tt_fig = ggplot(subset(all_points_tt), aes(x=log(x), y=y-60, color = cond, fill = cond)) + 
    xlab("Age (months)") +
  ylab("Perception thresholds (dB SNR)") +
   ggtitle("Buss et al. 2016: Two-talker noise",subtitle = "Children: n = 16, Adults: n = 10")+
   geom_smooth(method="lm") +
   geom_point(data = all_points_tt_adults, mapping = aes(x = log(x)),size = 6) +
   scale_color_manual(values = c("#d8b365", "#5ab4ac"),name = "Difficulty", labels = c("Easy","Difficult")) +
   scale_fill_manual(values=c("#d8b365", "#5ab4ac"),name = "Difficulty", labels = c("Easy","Difficult")) +
   theme_classic() +
   theme(axis.text=element_text(size=15),axis.title=element_blank(),legend.text=element_text(size=18),legend.title=element_text(size=18),plot.title = element_text(size = 20, face = "bold",hjust = 0.5),plot.subtitle = element_text(size = 14),
         panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', colour=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill='transparent',colour = NA),
        legend.box.background = element_rect(fill='transparent')) +
      scale_x_continuous(breaks =  c(1.609438,1.945910,2.197225,2.397895,2.564949,2.772589), labels = c("5","7","9","11","13","adults"), limits = c(1.504077 ,2.772589)) +
    ylim(-14,7)
buss_tt_fig

### Arrangement of the final figure
fig_litt_all = ggarrange(thre_children_figure,buss_ss_fig,buss_tt_fig,nrow = 1, common.legend = T,legend = "right")
fig_litt_all = annotate_figure(fig_litt_all, left = textGrob("Perception thresholds (dB SNR)", rot = 90, vjust = 0.25, gp = gpar(cex = 2.2)),
                    bottom = textGrob("Age in log(years)", gp = gpar(cex = 2.2)))

ggsave("fig_litt_all_log.png", plot = fig_litt_all,device = "png",width = 20,height = 7)

```


